left_gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - gripper_left_joint
  actuators:
    - gripper_left_motor
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    gripper_left_joint:
      goal: &goal_pos_constraint 0.02

  stop_trajectory_duration: 0.0
