satt_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 20000
      d: 1000
      i: 1
      i_clamp: 1
    joint2:
      p: 10000
      d: 2000
      i: 1
      i_clamp: 1
    joint3:
      p: 10000
      d: 2000
      i: 1
      i_clamp: 1
    joint4:
      p: 10000
      d: 2000
      i: 1
      i_clamp: 1
    joint5:
      p: 5000
      d: 100
      i: 1
      i_clamp: 1
    joint6:
      p: 5000
      d: 100
      i: 1
      i_clamp: 1