gazebo_ros_control:
  pid_gains:
    
    gripper_right_joint:
      p: 100
      i: 0.01
      d: 0.0
      i_clamp: 10
      torque_clamp: 100
    
    gripper_right_inner_double_joint:
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_fingertip_1_joint:
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_fingertip_2_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_motor_single_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_fingertip_3_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_inner_single_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_right_inner_double_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    gripper_left_joint:
      p: 100
      i: 0.01
      d: 0.0
      i_clamp: 10
      torque_clamp: 100
    
    gripper_left_inner_double_joint:
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_fingertip_1_joint:
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_fingertip_2_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_motor_single_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_fingertip_3_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_inner_single_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    gripper_left_inner_double_joint: 
      p: 20
      i: 0.01
      d: 0.0, 
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
 